server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  resources:
    cache:
      period: 0
    static-locations: file:src/main/resources/static/
