server:
  port: 8081

spring:
  profiles:
    active: dev
feign:
  client:
    config:
      default:
        connectionTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

api:
  transaction:
    url: http://localhost:8080

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p})  %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
